const Joi = require("joi")

const apartmentValidation = Joi.object({
  property_id: Joi.number().integer().required(),
  property_type: Joi.string().valid('apartment').default('apartment'),
  property_for: Joi.string().valid('commercial', 'residential', 'office'),
  property_name: Joi.string().required(),
  property_area: Joi.string(),
  listed_for: Joi.string().valid('sale', 'rent'),
  road_access: Joi.number(),
  bhk: Joi.string(),
  bedroom: Joi.number().integer(),
  bathroom: Joi.number().integer(),
  living_room: Joi.number().integer(),
  kitchen: Joi.number().integer(),
  dining: Joi.number().integer(),
  servant_quarter: Joi.number().integer(),
  store_room: Joi.number().integer(),
  extra_room: Joi.number().integer(),
  facing: Joi.string().valid('east', 'west', 'north', 'south', 'north-east', 'south-east', 'north-west', 'south-west'),
  province: Joi.string(),
  district: Joi.string(),
  municipality: Joi.string(),
  area_name: Joi.string(),
  ward: Joi.number().integer(),
  landmark: Joi.string(),
  latitude: Joi.number().precision(6),
  longitude: Joi.number().precision(6),
  price: Joi.number().integer().required(),
  price_per: Joi.string(),
  price_type: Joi.string().valid('fixed', 'negotiable'),
  furnish: Joi.string().valid('non-furnished', 'furnished', 'semi-furnished'),
  parking_bike: Joi.number().integer(),
  parking_car: Joi.number().integer(),
  amenities: Joi.object(),
  description: Joi.string(),
  social_media: Joi.object(),
  property_image: Joi.object(),
  approved_by: Joi.number().integer(),
  owner_id: Joi.number().integer(),
  owner_name: Joi.string(),
  owner_phone: Joi.string(),
  listing_type: Joi.string().valid('free', 'top', 'premium', 'featured').default('free'),
  status: Joi.string().valid('pending', 'approved', 'sold'),
});




const houseValidation = Joi.object({
  property_id: Joi.number().integer().required(),
  property_type: Joi.string().valid('house').default('house'),
  house_type: Joi.string(),
  built_up_area: Joi.number(),
  property_for: Joi.string().valid('commercial', 'residential', 'office'),
  property_name: Joi.string().required(),
  listed_for: Joi.string().valid('sale', 'rent'),
  land_area: Joi.string(),
  road_access: Joi.number(),
  pillar: Joi.number().integer(),
  phase_line: Joi.string(),
  material_used: Joi.string(),
  floor: Joi.number(),
  bedroom: Joi.number().integer(),
  kitchen: Joi.number().integer(),
  dining: Joi.number().integer(),
  bathroom: Joi.number().integer(),
  living_room: Joi.number().integer(),
  store: Joi.number().integer(),
  servant_quarter: Joi.number().integer(),
  pooja_room: Joi.number().integer(),
  extra_room: Joi.number().integer(),
  facing: Joi.string().valid('east', 'west', 'north', 'south', 'north-east', 'south-east', 'north-west', 'south-west'),
  province: Joi.string(),
  district: Joi.string(),
  municipality: Joi.string(),
  area_name: Joi.string(),
  ward: Joi.number().integer(),
  landmark: Joi.string(),
  latitude: Joi.number().precision(6),
  longitude: Joi.number().precision(6),
  price: Joi.number().integer().required(),
  price_per: Joi.string().valid('month', 'year', 'week'),
  price_type: Joi.string().valid('fixed', 'negotiable'),
  furnish: Joi.string().valid('non-furnished', 'furnished', 'semi-furnished'),
  parking_bike: Joi.number().integer(),
  parking_car: Joi.number().integer(),
  amenities: Joi.object(),
  description: Joi.string(),
  social_media: Joi.object(),
  property_image: Joi.object(),
  approved_by_id: Joi.number().integer(),
  owner_id: Joi.number().integer(),
  owner_name: Joi.string(),
  owner_phone: Joi.string(),
  listing_type: Joi.string().valid('free', 'top', 'premium', 'featured').default('free'),
  status: Joi.string().valid('pending', 'approved', 'sold'),
});




const landValidation = Joi.object({
  property_id: Joi.number().integer().required(),
  property_type: Joi.string().valid('land').default('land'),
  property_for: Joi.string().valid('non-plotted', 'plotted'),
  property_name: Joi.string().required(),
  land_area: Joi.string(),
  moda: Joi.string(),
  listed_for: Joi.string().valid('sale', 'rent'),
  twist: Joi.number(),
  road_access: Joi.number(),
  facing: Joi.string().valid('east', 'west', 'north', 'south', 'north-east', 'south-east', 'north-west', 'south-west'),
  province: Joi.string(),
  district: Joi.string(),
  municipality: Joi.string(),
  area_name: Joi.string(),
  ward: Joi.number().integer(),
  landmark: Joi.string(),
  latitude: Joi.number().precision(6),
  longitude: Joi.number().precision(6),
  price: Joi.number().integer().required(),
  price_for: Joi.string(),
  price_type: Joi.string().valid('fixed', 'negotiable'),
  amenities: Joi.object(),
  description: Joi.string(),
  social_media: Joi.object(),
  property_image: Joi.object(),
  approved_by: Joi.number().integer(),
  owner_id: Joi.number().integer(),
  owner_name: Joi.string(),
  owner_phone: Joi.string(),
  listing_type: Joi.string().valid('free', 'top', 'premium', 'featured').default('free'),
  status: Joi.string().valid('pending', 'approved', 'sold'),
});

const validateSchema={
    "apartment":async (property)=>await apartmentValidation.validateAsync(property),
    "house":async(property)=>await houseValidation.validateAsync(property),
    "land":async(property)=>await landValidation.validateAsync(property)
  }

module.exports = {validateSchema}
